organization: waldirborbajr # org name on holopin
defaultSticker: cla3akind199908mqwq5zssov # sticker ID
stickers:
  -
    id: cla3akind199908mqwq5zssov # sticker id
    alias: Surfer-Moby-Dock_from-docker # shorthand-string
