# .golangci.yml
run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  concurrency: 0

output:
  color: true
  formats:
    colored-line-number:
      path: stdout
  print-linter-name: true
  show-stats: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-dirs:
    - vendor
    - testdata
    - mocks
    - internal/mocks
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - unparam
    - linters:
        - revive
      text: "line-length-limit"
    - path: "_test\\.go$"
      linters:
        - gosec

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  disable-all: false
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - performance
    - style
    - test
    - unused

linters-settings:
  gosec:
    excludes:
      - G101
      - G115
    severity: "warning"
  revive:
    rules:
      - name: exported
        disabled: false
      - name: errorf
        disabled: false
  goimports:
    local-prefixes: "github.com/waldirborbajr/kvstok"
  misspell:
    locale: US
  staticcheck:
    checks:
      - all
      - "-SA1019"
  govet:
    disable:
      - shadow
