run:
  go: 1.19

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoglobals
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - prealloc
    - staticcheck
    - testpackage
    - typecheck
    - unparam
    - unused
    - wsl
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Start` is not checked
    - Error return value of `.*Stop` is not checked
    - Error return value of `.*Write` is not checked