before:
  hooks:
    - go mod tidy

builds:

  - main: ./main.go
    binary: kvstok
    id: kvstok-cli

    env:
      - CGO_ENABLED=0

    goos: [ windows,linux,darwin ]
    goarch: [ amd64,386,arm,arm64 ]
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

    flags:
      - -trimpath

archives:
  - format: zip
    id: gsolc-select
    replacements:
      darwin: macOS

checksum:
  algorithm: sha256