
Output assets/demo.gif

Set TypingSpeed 75ms
Set FontSize 22
Set Width 1300
Set Height 650

Type "echo 'Welcome to KVStoK Demonstration!'"

Sleep 500ms

Enter

Sleep 2s

Type "kvstok addkv user myusername"

Sleep 500ms

Enter

Sleep 2s

Type "kvstok addkv secret1 ultrasecretkey"

Sleep 500ms

Enter

Sleep 2s

Type "kvstok addkv secret2 tokensecret"

Sleep 500ms

Enter

Type "kvstok listkv"

Sleep 500ms

Enter

Sleep 5s
