name: 🐕 Review DOG

on:
  repository_dispatch:
    types: [trigger-review-dog]

jobs:
  golangci-lint:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2

      - name: Trigger Test
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-build-test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
