name: 🔨 Build Test CI

on:
  repository_dispatch:
    types: [trigger-build-test]
  # push:
  #   branches:
  #     - '**'
  # pull_request:
  #   branches:
  #     - '**'

jobs:

  build:
    name: Test Builds
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build KVStoK
        run: go build -v ./...
        working-directory: .

      - name: Testing KVStoK
        run: go test ./... -race
        working-directory: .

