name: 🔨 Build & Test

on:
  repository_dispatch:
    types: [trigger-build-test]

  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  tests:
    name: Running Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'

    - name: Testing KVStoK
      run: go test ./... -race
      working-directory: .

  build:
    - name: Running Build
    needs: tests
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
      working-directory: .

    - name: Building KVStoK
      run: go build -v ./...
      working-directory: .
