name: 🎉 Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          cache: true
      - run: go mod tidy
      - run: go test -v ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
          workdir: cmd/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
